# test/matrix.py

import pytest
import numpy as np
import sdp.framework_KH

def assert_matrix_is_hermitian(M: np.ndarray, rtol: float = 1e-5, atol: float = 1e-8):
    """
    Tests if the input matrix M is Hermitian.

    Args:
        M: The matrix to be tested.
        rtol: Relative tolerance for the comparison (default: 1e-5).
        atol: Absolute tolerance for the comparison (default: 1e-8).
    
    Raises:
        AssertionError: If M is not 2D, not square, or not Hermitian within tolerance.
    """
    M = np.asarray(M)
    assert M.ndim == 2, f"L'input must be 2D matrix, received {M.ndim} dimensions."
    assert M.shape[0] == M.shape[1], f"The matrix must be square, received dimensions: {M.shape}."
    assert np.allclose(M, M.conj().T, rtol=rtol, atol=atol), "The matrix does not match its conjugate transpose."

def test_phase_error_cost_matrix_is_hermitian():
    """
    Test to ensure that the phase error cost matrix generated by the framework_KH class is Hermitian.
    """
    d = 4  # Example dimension
    QBER_Z = 0.05  # Example QBER
    total_coincidences = 100000  # Example total coincidences
    visibility_X = 0.88  # Example visibility

    fKH = sdp.framework_KH.FrameworkKH(d, QBER_Z, total_coincidences, visibility_X)
    C = fKH.C

    assert_matrix_is_hermitian(C)

